### PR TITLE
Legger til Supply Chain Levels for Software Artifacts (SLSA) 

### PR DESCRIPTION
**Pull request by blommish**
https://doc.nais.io/security/salsa/salsa/

Dev:
https://salsa.dev-gcp.nav.cloud.nais.io/projects/ffac79b2-2086-4103-bfd1-1099749fd00b (login med openid)
Prod
https://salsa.prod-gcp.nav.cloud.nais.io/

`#nais-announcements` 
https://nav-it.slack.com/archives/C01DE3M9YBV/p1686213842792209

Virker som at bygging av docker-image går fra 15 til 60s
https://github.com/navikt/familie-ef-sak/actions/runs/5219504825/jobs/9421412620

### CODE REVIEW

**Comment by blommish** [comment]
Burde vi kanskje legge til denne? https://nav-it.slack.com/archives/C01DE3M9YBV/p1686434590290359?thread_ts=1686213842.792209&cid=C01DE3M9YBV

**Comment by throndi** [comment]
> Burde vi kanskje legge til CycloneDx? https://nav-it.slack.com/archives/C01DE3M9YBV/p1686434590290359?thread_ts=1686213842.792209&cid=C01DE3M9YBV

For visualisering av grafen ?

**Review by ViktorGSolberg — APPROVED** [review]
Bra! 🔒

**Comment by ViktorGSolberg** [comment]
> Burde vi kanskje legge til CycloneDx? https://nav-it.slack.com/archives/C01DE3M9YBV/p1686434590290359?thread_ts=1686213842.792209&cid=C01DE3M9YBV

Ja, det så ganske rett frem ut: 
`<plugins>
        <plugin>
            <groupId>org.cyclonedx</groupId>
            <artifactId>cyclonedx-maven-plugin</artifactId>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>makeAggregateBom</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
`

**Comment by blommish** [comment]
> > Burde vi kanskje legge til CycloneDx? https://nav-it.slack.com/archives/C01DE3M9YBV/p1686434590290359?thread_ts=1686213842.792209&cid=C01DE3M9YBV
> 
> For visualisering av grafen ?

Yep

**Review by throndi — APPROVED** [review]

**Pull request merged**
